run:
  timeout: 5m
  tests: true
  skip-dirs:
    - example

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - inamedparam
    - nakedret
    - nolintlint
    - nonamedreturns
    - varnamelen
    - wrapcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/alexeyco/ydbm)
    section-separators:
      - newLine

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - funlen