name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.x
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -race -tags fast -coverprofile unit.txt -covermode atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./unit.txt
          flags: unit,${{ matrix.os }},${{ matrix.go-version }}
          name: unit
